version: '3'
services:
  dashboard-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashboard-app
    ports:
      - "80:80"
    networks:
      - production
  dashboard-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dashboard-backend
    ports:
      - "3000:3000"
    networks:
      - production

networks:
  production:
    driver: bridge